# Generated by Django 3.1.7 on 2021-03-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='timeline/images/')),
                ('short_description', models.CharField(max_length=500)),
                ('story', models.TextField()),
                ('moved_in', models.DateField()),
                ('moved_out', models.DateField()),
            ],
        ),
    ]
